[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#1a73e8"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#202124"
font = "sans serif"
